-------------------------------------------------------------------------------
-- Title      : Successive Approximation Register
-- Project    : FABulous Analogue Interface (FAIf) for HeiChips 2026
-------------------------------------------------------------------------------
-- File       : sar.vhdl
-- Author     : Torsten Maehne  <torsten.maehne@bfh.ch>
-- Company    : BFH-EIT
-- Created    : 2026-08-06
-- Last update: 2026-08-06
-- Platform   : GHDL + Yosys
-- Standard   : VHDL'93/02, Math Packages
-------------------------------------------------------------------------------
-- Description:
--
-- This entity implements the Successive Approximation Register (SAR)
-- for a SAR Analogue to Digital Converter (ADC). The block has a
-- low-active asynchronous reset and a high-active synchronous clear
-- for the internal value and mask registers, which have priority over
-- the other sequential behaviour. If the `ena` input is '0', then the
-- internal value and mask registers are not updated at the rising edge
-- of clock. Setting `start` to high for at least a clock cycle, will
-- start the conversion. During the conversion, the `done` output is
-- low. The SAR will start progressively setting/clearing the bits of
-- its internal value register starting from the MSB down to the
-- LSB. That value register constitutes the reference value for the DAC
-- that generates the comparison voltage during conversion. An
-- analogue comparator compares the voltage at the sample & hold
-- output with the reference voltage generated by the DAC. Its output
-- is connected to the `comp` input of the SAR. First, the MSB is set
-- to '1'. At each subsequent clock cycle, the `comp` input is checked
-- and the next bit in direction to LSB is set to '1'. If the `comp`
-- input is '0' then the previous set bit is cleared, i.e., set to
-- '0'. Once the decision for the LSB value is made, the conversion is
-- done and the `tick` output is set to '1' for one clock cycle. The
-- `done` output is always at '1' when the SAR is idle, i.e., no
-- conversion is in progress. The `value` output is also connected to
-- the internal value register, i.e., it shows the conversion in
-- progress.
--
-------------------------------------------------------------------------------
-- Copyright (c) 2026 HeiChips 2026 FAIf team
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author  Description
-- 2026-08-06  1.0      maehne	Created
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity sar is
  
  generic (
    NBITS : positive := 8);             -- SAR register width

  port (
    clk   : in  std_logic;              -- clock input
    rst_n : in  std_logic;              -- low-active asynchronous reset
    clear : in  std_logic;              -- high-active synchronous clear
    ena   : in  std_logic;              -- enable input
    start : in  std_logic;              -- start conversion
    done  : out std_logic;              -- conversion done
    tick  : out std_logic;  -- one clock cycle pulse at end of conversion
    value : out std_logic_vector(NBITS-1 downto 0);   -- conversion value
    -- Interface to the analogue domain -> requires level conversion
    hold  : out std_logic;              -- activates the sample & hold block
    ref   : out std_logic_vector(NBITS-1 downto 0);   -- reference value for DAC
    comp  : in  std_logic);             -- input from the analogue comparator

end entity sar;

--------------------------------------------------------------------------------

architecture rtl of sar is
  -- Value register to hold the converted ADC value
  signal value_reg, value_next : std_logic_vector(NBITS-1 downto 0);
  -- Mask register for setting/clearing bits in the value register.
  -- The mask register is one-hot during conversion. If all bits in
  -- the mask register are set to '0', the SAR is idle/the conversion
  -- is done.
  signal mask_reg, mask_next : std_logic_vector(NBITS downto 0);
  constant MASK_ZERO : std_logic_vector(mask_reg'range) := (others => '0');
begin  -- architecture rtl

  -- purpose: describe the registers
  -- type   : sequential
  -- inputs : clk, rst_n, clear, ena, value_next, mask_next
  -- outputs: value_reg, mask_reg
  REG: process (clk, rst_n) is
  begin  -- process REG
    if rst_n = '0' then                 -- asynchronous reset (active low)
      value_reg <= (others => '0');
      mask_reg <= (others => '0');
    elsif rising_edge(clk) then
      value_reg <= value_next;
      mask_reg <= mask_next;
    end if;
  end process REG;

  -- purpose: describe the next state of the registers
  -- type   : combinational
  -- inputs : value_reg, mask_reg, clear, start, ena, comp
  -- outputs: value_next, mask_next
  NSL: process (value_reg, mask_reg, clear, start, ena, comp) is
    -- temporary value to facilitate clearing/setting of the bits
    variable value_temp  : std_logic_vector(value_reg'range);
  begin  -- process NSL
    value_next <= value_reg;
    value_temp := value_reg;
    mask_next <= mask_reg;
    if clear = '1' then
      value_next <= (others => '0');
      mask_next <= (others => '0');
    elsif ena = '1' then
      if mask_reg = MASK_ZERO then
        if start = '1' then
          value_next <= (others => '0');
          mask_next <= (others => '0');
          mask_next(NBITS) <= '1';
        end if;
      else
        mask_next <= '0' & mask_reg(NBITS downto 1);
        if comp = '0' then
          -- Clear bit based on the current analogue comparison
          value_temp := value_reg and not mask_reg(NBITS-1 downto 0);
        end if;
        -- Set bit for the next analogue comparison;
        value_next <= value_temp or mask_reg(NBITS downto 1);
      end if;
    end if;
  end process NSL;

  -- output logic
  done <= '1' when mask_reg = MASK_ZERO else
          '0';
  tick <= '1' when ena = '1' and mask_reg(0) = '1' and mask_next = MASK_ZERO else
          '0';
  value <= value_reg;
  hold <= '1' when mask_reg /= MASK_ZERO else
          '0';
  ref   <= value_reg;

end architecture rtl;

--------------------------------------------------------------------------------
